bounswe/bounswe2025group6

Issue/issue_example.md, Issue/issue_rules.md
Added issue rules to standardize and streamline our process. These guidelines will be followed for issue creation, tracking, and resolution to ensure consistency and clarity across the project.
=> Add issue rules

README.md
Linked team members' names to their personal wiki pages
=> README is updated

.github/Branchin_guide.md, .github/Issue_template.md, .github/Pr_template.md
- Added **Pull Request** and **Issue Templates** under a `.github` directory to standardize contributions.
- Introduced a **Branching Guide** to promote a more organized and consistent development workflow.
=> Add pr and issue templates, and branch guide

backend/fithub/api/README.md, backend/fithub/api/models.py, backend/fithub/api/serializers.py, backend/fithub/api/tests.py, backend/fithub/api/urls.py, backend/fithub/api/views.py, backend/fithub/api_documentations/dietition_registration.md, backend/fithub/api_documentations/email_verify_and_notifications.md, backend/fithub/api_documentations/user_registration.md, backend/fithub/fithub/settings.py, backend/fithub/misc/test.rest, backend/fithub/misc/test_curl.txt
This update to the registration system introduces support for **regular users** and **dietitians**. Dietitians are required to provide a certification URL to prove their education. In addition, a process for **email verification** has been implemented, ensuring that users can only log in after verifying their email addresses.
1.  **User Registration**: Regular users can now register through the same endpoint.
2.  **Dietitian Registration**: Dietitians now have a registration process that includes providing a certification URL to verify their credentials.
3.  **Email Notifications**: A Gmail account has been set up to send email notifications for account verification.
4.  **Email Verification**: A new endpoint allows users to verify their email addresses before they can log in.
---------- …
=> User and Dietitian Registration and Email Verification

mobile/lib/screens/forgot_pass_screen.dart, mobile/lib/screens/login_screen.dart, mobile/test/widget_test.dart
---
- Created forgot password screen
- Link it with the login screen
- Added unit tests for the widgets
---
---
---
=> Created forgot password screen

mobile/android/app/build.gradle.kts, mobile/ios/Flutter/Debug.xcconfig, mobile/ios/Flutter/Release.xcconfig, mobile/ios/Podfile, mobile/lib/screens/forgot_pass_screen.dart, mobile/lib/screens/login_screen.dart, mobile/lib/screens/new_password_screen.dart, mobile/lib/screens/register_screen.dart, mobile/lib/screens/verify_code_screen.dart, mobile/pubspec.lock, mobile/pubspec.yaml, mobile/test/new_password_screen_test.dart, mobile/test/register_screen_test.dart, mobile/test/verify_code_screen_test.dart, mobile/test/widget_test.dart
---
- Created `RegisterScreen` with user type selection and PDF upload for dietitians
- Created `VerifyCodeScreen` for entering 6-digit verification code sent via email
- Created `CreateNewPasswordScreen` to reset user password
- Connected "Create Account" button to `RegisterScreen`
- Applied `AppTheme` color scheme across all new screens
---
_(no new endpoints implemented in this PR — UI level changes only)_
---
---
- Widget tests were written for all screens: Register, Verify Code, and Create New Password
- All UI elements are responsive and consistent with the app's theme
=> M 002 seyit register page

backend/docs/ingredients_documentations/ingredient_get.md, backend/fithub/ingredients/serializers.py, backend/fithub/ingredients/urls.py, backend/fithub/ingredients/views.py
---
- Implemented the **Get Ingredient ID by Name** endpoint (`GET /ingredients/get-id-by-name`).
- Implemented the **Get Ingredient by Name** endpoint (`GET /ingredients/get-ingredient-by-name/`
- Added documentation for both endpoints.
---
- GET /ingredients/get-id-by-name
- GET /ingredients/get-ingredient-by-name/
---
---
- The new endpoints allow users to retrieve ingredient id or full details of the ingredient by **name** 
- Please review the endpoint documentation for accuracy.
---
=> Ingredient endpoints update, get id, get ingredient by name

backend/fithub/fithub/settings.py, mobile/lib/screens/register_screen.dart, mobile/lib/services/auth_service.dart, mobile/test/mocks/mock_auth_service.dart, mobile/test/register_screen_test.dart
[158](https://github.com/bounswe/bounswe2025group6/issues/158)
---
- Fixed Django settings to enable emulator connection for proper network access.
- Corrected the Django base URL error in `AuthService` to ensure accurate API calls.
- Connected the `register` functionality to the backend for seamless user registration.
---
- POST /api/register (connected the register functionality to the backend)
---
---
- Please review the emulator connection fix to ensure it works across different environments.  
- The base URL fix in `AuthService` might need additional testing with other endpoints.
=> connect register to backend

app/frontend/src/components/auth/ProtectedRoute.jsx, app/frontend/src/contexts/AuthContext.jsx, app/frontend/src/pages/auth/EmailVerificationPage.jsx, app/frontend/src/pages/auth/ForgotPasswordPage.jsx, app/frontend/src/pages/auth/LoginPage.jsx, app/frontend/src/pages/auth/RegisterPage.jsx, app/frontend/src/pages/auth/ResetPasswordPage.jsx, app/frontend/src/routes/index.jsx, app/frontend/src/services/authService.js, app/frontend/src/styles/AuthPages.css
[200](https://github.com/bounswe/bounswe2025group6/issues/200)
---
- Implemented complete JWT authentication flow for frontend-backend communication
- Changed frontend forms for user login and registration with validation
- Added support for both regular user and dietitian registration
- Integrated email verification process with backend
- Implemented password reset functionality with two methods (email link and verification code)
- Added consistent styling for all authentication pages
- Created utility functions for JWT token handling and storage
- Updated routing to include authentication-related routes
- Improved error handling and user feedback
---
- POST /api/register/ - For user registration
- POST /api/login/ - For user authentication
- GET /api/verify-email/{token}/ - For email …
=> Implement authentication for login/register flow

app/frontend/src/pages/auth/ForgotPasswordPage.jsx
---
- 
-
---
- POST /api/recipes
- DELETE /api/recipes/{id}
---
---
- 
---
=> "bugfix in forgot password page"

backend/docs/api_documentations/authentication/forgot password 6 digit code version.md, backend/fithub/api/models.py, backend/fithub/api/serializers.py, backend/fithub/api/urls.py, backend/fithub/api/views.py, backend/fithub/docker-compose.yml, backend/fithub/misc/test.rest, backend/fithub/requirements.txt
This PR refactors the existing password reset functionality into a more secure and modular three-step process:
1.  **Request Reset Code:** Users can request a 6-digit reset code sent to their registered email.
2.  **Verify Reset Code:** Users verify the received code to confirm their identity.
3.  **Set New Password:** Upon successful verification, users set a new password for their account.
This separation enhances security and aligns with best practices for password reset flows.
**Changes:**
-   Introduced separate endpoints for requesting a reset code, verifying the code, and setting a new password.
-   Updated serializers and views to support the new workflow.
-   Implemented token generation upon successful code verification.
-   Updated API documentation to reflect the changes.
=> B 0012 ozgur forgot password revision

mobile/lib/screens/dashboard_screen.dart, mobile/lib/screens/forgot_pass_screen.dart, mobile/lib/screens/login_screen.dart, mobile/lib/screens/new_password_screen.dart, mobile/lib/screens/verify_code_screen.dart, mobile/lib/services/auth_service.dart, mobile/pubspec.lock, mobile/pubspec.yaml, mobile/test/dashboard_screen_test.dart, mobile/test/forgot_password_screen_test.dart, mobile/test/login_screen_test.dart, mobile/test/mocks/mock_auth_service.dart, mobile/test/new_password_screen_test.dart, mobile/test/register_screen_test.dart, mobile/test/verify_code_screen_test.dart
---
- Dashboard UI implemented.
- Password reset APIs changed. 
- Added dashboard UI tests
- Updated reset password tests
---
---
- Some tests fail. It is not caused by the features themselves, the tests have issues. They will be fixed later. 
---
=> Implement Dashboard Page of the mobile app

backend/docs/api_documentations/authentication/user viewset.md, backend/fithub/api/models.py, backend/fithub/api/serializers.py, backend/fithub/api/tests.py, backend/fithub/api/urls.py, backend/fithub/api/views.py, backend/fithub/core/models.py, backend/fithub/ingredients/models.py, backend/fithub/misc/test.rest, backend/fithub/recipes/models.py, backend/fithub/requirements.txt
---
- Generic CRUD endpoints for the RegisteredUserViewSet implementED.
- Bookmark and Follow/Unfollow Endpoints ADDED
---
- **GET** `/users/`
- **POST** `/users/`
- **GET** `/users/{id}/`
- **PUT** `/users/{id}/`
- **PATCH** `/users/{id}/`
- **DELETE** `/users/{id}/`
- `GET /users/get_user_id_by_email/`
- `POST /users/follow/`
- `POST /users/bookmark_recipe/`
---
---
=> User profile endpoints implemented

practice-app/frontend/src/pages/auth/ForgotPasswordPage.jsx, practice-app/frontend/src/services/authService.js
--- #227 
- Name mismatches are fixed
- Token for verification is added
---
- POST /api/verify-reset-code
- POST /api/reset-password
- POST /api/request-password-reset-code
- POST /api/token
- POST /api/token/refresh
---
---
-  Forget password functionality works perfect without any error.
---
=> Forget password fixed, finalized

practice-app/backend/fithub/package-lock.json, practice-app/docker-compose.yml, practice-app/frontend/src/pages/ingredients/IngredientsPage.jsx, practice-app/frontend/src/styles/IngredientsPage.css
Enhancement of Ingredients Page UI and functionality
---
- Enhanced UI transitions for page size changes with smooth fade effects
- Reorganized code structure with clear section comments
- Moved all inline styles to IngredientsPage.css
- Improved pagination controls with better disabled state handling
- Added automatic page reset (to page 1) when changing page size
- Optimized loading states to prevent screen flicker
- Improved search functionality display
---
---
- The changes focus on improving user experience with smoother transitions
- Search and pagination now work independently without interfering with each other
- Loading states are more user-friendly without unnecessary screen flashes
- Component structure is now more maintainable with clear section organization
---
*Note: No …
=> FRONTEND: Enhancement of Ingredients Page UI and functionality

practice-app/frontend/src/components/recipe/RecipeCard.jsx, practice-app/frontend/src/pages/recipes/RecipeDiscoveryPage.jsx, practice-app/frontend/src/routes/index.jsx, practice-app/frontend/src/services/recipeService.js
--- #236 
- RecipeCard.jsx updated
- RecipeDİscoveryPage.jsx updated
---
- GET/api/recipes
---
---
- 
---
=> recipe listing done

practice-app/frontend/src/pages/community/CommunityPage.jsx, practice-app/frontend/src/pages/community/PostDetailPage.jsx, practice-app/frontend/src/services/userService.js
- [Display User Names in Community Forum](https://github.com/bounswe/bounswe2025group6/issues/245)
- Created userService.js to fetch user details from the backend
- Updated CommunityPage.jsx to display real usernames for post authors
- Updated PostDetailPage.jsx to display real usernames for post authors and commenters
- Implemented efficient caching mechanism to minimize API calls
- Added fallback handling for cases where user data can't be retrieved
- Integrated with GET /api/users/{id}/ endpoint for user data
- This PR enhances user experience by displaying real usernames in the forum instead of generic User #ID labels
- The implementation includes a caching system to optimize performance and minimize API calls
=> feat: display usernames instead of user IDs in forum components

practice-app/backend/fithub/api/serializers.py, practice-app/frontend/src/pages/DashboardPage.jsx, practice-app/frontend/src/pages/auth/ForgotPasswordPage.jsx, practice-app/frontend/src/pages/recipes/RecipeDiscoveryPage.jsx
---
- Forget password method is determined as 6 digit verification code
- New password cannot be same with the older one
- Dashboard cleaned
---
- POST/api/reset-password
---
---
- There is a change in backend code too, so reviewer should be careful about conflicts (if there is)
---
=> F 0010 muhammed general fixations

mobile/lib/models/ingredient.dart, mobile/lib/models/recipe.dart, mobile/lib/models/user_profile.dart, mobile/lib/screens/dashboard_screen.dart, mobile/lib/screens/discover_recipes_screen.dart, mobile/lib/screens/login_screen.dart, mobile/lib/screens/profile_screen.dart, mobile/lib/screens/profile_settings_screen.dart, mobile/lib/screens/recipe_detail_screen.dart, mobile/lib/screens/register_screen.dart, mobile/lib/screens/upload_recipe_screen.dart, mobile/lib/services/auth_service.dart, mobile/lib/services/profile_service.dart, mobile/lib/services/recipe_service.dart, mobile/lib/services/storage_service.dart, mobile/lib/widgets/recipe_card.dart, mobile/pubspec.lock, mobile/test/mocks/mock_profile_service.dart, mobile/test/profile_screen_test.dart
[profile page](https://github.com/bounswe/bounswe2025group6/issues/216)
[recipes feature](https://github.com/bounswe/bounswe2025group6/issues/215)
---
- Created the **Recipe Page** and connected it to the backend  
- Implemented the **Add Recipe** feature with backend integration  
- Connected the **Profile Page** to the backend  
---
- `GET /recipes/` — List all recipes  
- `POST /recipes/` — Create a new recipe  
- `GET /recipes/{id}/` — Get recipe details by ID  
- `PUT /recipes/{id}/` — Update a recipe  
---
---
- Let me know if any UI adjustments are needed or if more fields should be added . I need to add some tests for further development
=> profile page - recipes page 

mobile/lib/models/login_response.dart, mobile/lib/services/auth_service.dart, mobile/test/login_screen_test.dart, mobile/test/mocks/mock_auth_service.dart
fix
---
add fix for authentication problem
- 
-
---
---
---
- 
quick fix related to profile page problem
---
=> fix for auth

practice-app/backend/docs/api_documentations/authentication/login.md, practice-app/backend/fithub/api/views.py, practice-app/backend/fithub/recipes/models.py
---
This PR includes several improvements and bug fixes across the API:
-   ➕ **Swagger Tags**: Added descriptive tags to endpoints for better Swagger UI grouping.
-   🛠️ **Swagger Fix**: Resolved documentation rendering issue for `RecipeRatingViewSet`.
-   🔐 **Login Enhancement**: Included `username` in the login response for easier frontend handling.
-   🐞 **Recipe Bug Fix**: Fixed a minor DB-related bug in the recipe update endpoint.
---
---
---
- 
---
=> Add Swagger Tags, Enhance Login Response, and Fix Recipe Update Bug

practice-app/frontend/src/pages/recipes/RecipeDetailPage.jsx, practice-app/frontend/src/styles/RecipeDetailPage.css
---
- RecipeDetailPage.jsx bug fixed and added some extra columns
---
- GET/api/recipes
---
---
- 
---
=> RecipeDetailPage updated

practice-app/frontend/src/components/ui/Button.jsx, practice-app/frontend/src/pages/DashboardPage.jsx, practice-app/frontend/src/pages/auth/LoginPage.jsx, practice-app/frontend/src/pages/community/CommunityPage.jsx, practice-app/frontend/src/pages/community/CreatePostPage.jsx, practice-app/frontend/src/pages/community/PostDetailPage.jsx, practice-app/frontend/src/styles/AuthPages.css, practice-app/frontend/src/styles/CommunityPage.css, practice-app/frontend/src/styles/CreatePostPage.css, practice-app/frontend/src/styles/DashboardPage.css, practice-app/frontend/src/styles/HomePage.css, practice-app/frontend/src/styles/Layout.css, practice-app/frontend/src/styles/PostDetailPage.css
---
- Enhanced Dashboard UI with improved layout and responsive design
- Fixed Navbar responsiveness issues and maintained stable layout until reasonable minimum width
- Updated Community Forum UI:
- Added dynamic vote button colors (green for upvotes, red for downvotes)
- Improved post card styling and readability
- Enhanced overall visual hierarchy
- Improved Create Post page:
- Updated form styling for better user experience
- Added consistent color scheme with community theme
- Enhanced Post Detail page:
- Added refined comment card styling with hover effects
- Implemented dynamic vote button interactions with visual feedback
- Updated colors to match community theme (#b67979)
- Improved spacing and typography
- Added responsive design improvements across all pages
- Implemented …
=> community-and-dashboard-ui-improvements

practice-app/frontend/src/pages/recipes/RecipeDetailPage.jsx, practice-app/frontend/src/pages/recipes/UploadRecipePage.jsx, practice-app/frontend/src/styles/RatingStars.css, practice-app/frontend/src/styles/RecipeDetailPage.css, practice-app/frontend/src/styles/style.css
---
- RecipeDetailPage.css file changed.
- UploadRecipePage.jsx bug fixed
---
---
---
- 
---
=> style RecipeDetailPage.jsx

mobile/lib/screens/community/community_screen.dart, mobile/lib/screens/community/post_detail_screen.dart, mobile/lib/services/community_service.dart
---
- Implemented upvote/downvote login in the community page
- Connected with the backend
- Tested it with multiple accounts
---
---
- Unit tests will be added later.
---
=> Implemented upvote/downvote feature on the community page

practice-app/frontend/src/layouts/AuthLayout.jsx, practice-app/frontend/src/layouts/MainLayout.jsx, practice-app/frontend/src/styles/Layout.css
---
- navbar view is changed
---
---
---
- 
---
=> style navbar

practice-app/frontend/src/layouts/MainLayout.jsx, practice-app/frontend/src/pages/DashboardPage.jsx, practice-app/frontend/src/pages/recipes/RecipeDetailPage.jsx, practice-app/frontend/src/pages/recipes/RecipeEditPage.jsx, practice-app/frontend/src/routes/index.jsx, practice-app/frontend/src/services/authService.js, practice-app/frontend/src/services/userService.js
---
- handleDelete function is improved, it checks for current user id and creator id of recipe match
- Edit recipe functionality is added.
- Only creator of recipe can edit the recipe
- fetchUserName method is implemented, Dashboard displays username.
- Small icons are added to the navBar
---
- GET api/get-user-id/
- DELETE /recipes/{id}/
- PUT /recipes/{id}
---
---
- 
---
=> F 0012 muhammed recipe fixations

mobile/lib/screens/profile_screen.dart, mobile/lib/screens/upload_recipe_screen.dart, mobile/lib/services/recipe_service.dart, mobile/pubspec.lock, mobile/pubspec.yaml
[profile](https://github.com/bounswe/bounswe2025group6/issues/216)
---
- My recipes to profile is added
- Ingredients search functionality is improved
- Some fixes are added
---
- `GET /api/recipes`
---
---
- if there is any error, feel free to contact me.
=> profile my recipes -ingredients list-some fixes

practice-app/backend/fithub/ingredients/views.py, practice-app/frontend/src/layouts/AuthLayout.jsx, practice-app/frontend/src/layouts/MainLayout.jsx, practice-app/frontend/src/pages/auth/RegisterPage.jsx, practice-app/frontend/src/pages/community/CommunityPage.jsx, practice-app/frontend/src/pages/community/PostDetailPage.jsx, practice-app/frontend/src/pages/recipes/RecipeDiscoveryPage.jsx, practice-app/frontend/src/styles/AuthPages.css, practice-app/frontend/src/styles/CommunityPage.css, practice-app/frontend/src/styles/Layout.css, practice-app/frontend/src/styles/PostDetailPage.css, practice-app/frontend/src/styles/RecipeDiscoveryPage.css
---
Frontend Changes:
- Enhanced navbar styling with consistent spacing and responsive design
- Added clickable usernames in community forum for profile navigation
- Updated password validation with secure requirements (8+ chars, uppercase, lowercase, number)
- Updated logo styling in main layout
- Improved form validation feedback
Backend Changes:
- Added ordering to Ingredient model to fix pagination warning
- Enhanced error handling in API endpoints
UI/UX Improvements:
- Consistent color scheme across components
- Enhanced button states and transitions
- Better visual feedback for user interactions
- Improved error messages and validation feedback
---
- GET /ingredients/wikidata/image/
---
=> add ingredient image endpoint and implement UI improvements and fixes

practice-app/backend/fithub/ingredients/views.py
---
- Added description endpoint by external WikiData API.
- Added Swagger documentation accordingly.
---
-  **Endpoint**:  `GET /wikidata/category/`
---
---
=> add external api

practice-app/backend/fithub/ingredients/views.py
---
- Implemented an endpoint to get the origin country/cuisine of a meal from Wikidata.
---
- GET /ingredients/wikidata/origin/
---
---
- 
---
=> Implement an endpoint - Ali

practice-app/backend/fithub/ingredients/views.py
---
- Implemented an endpoint to retrieve the Wikidata label for a specific ingredient.
---
- GET /ingredients/wikidata/wikidata_label/
---
---
- 
---
=> Implement an endpoint - Bahadir

practice-app/backend/fithub/ingredients/views.py
Implement Wikidata Label Filtering for Ingredients
---
- Implemented new API endpoint to filter ingredients by their Wikidata label
- Added case-insensitive search functionality using `icontains` for more flexible matching
- Added proper error handling for missing query parameters and no results cases
- Implemented serialization of filtered ingredients using WikidataInfoSerializer 
- Added Swagger documentation for the new endpoint with parameter descriptions
---
- GET /ingredients/filter-by-label - Filter ingredients by Wikidata label
---
---
- The endpoint performs a case-insensitive search using `icontains` to provide more flexible matching
- The endpoint returns a 400 error if the required 'label' parameter is missing
- The endpoint returns a 404 error if no ingredients match the …
=> feat(api): add endpoint to filter ingredients by Wikidata label

practice-app/frontend/src/pages/recipes/RecipeDetailPage.jsx, practice-app/frontend/src/pages/shopping/ShoppingListPage.jsx, practice-app/frontend/src/styles/RecipeCard.css, practice-app/frontend/src/styles/RecipeDetailPage.css
---
- Bugs on Recipe pages are fixed.
---
---
---
- 
---
=> Some style bugs fixed

practice-app/frontend/babel.config.js, practice-app/frontend/jest.config.js, practice-app/frontend/package-lock.json, practice-app/frontend/package.json, practice-app/frontend/src/__tests__/Button.test.jsx, practice-app/frontend/src/__tests__/ImageUploader.test.jsx, practice-app/frontend/src/__tests__/IngredientList.test.jsx, practice-app/frontend/src/test/mocks/fileMock.js, practice-app/frontend/src/test/mocks/mockRecipeService.js, practice-app/frontend/src/test/mocks/mockToast.js, practice-app/frontend/src/test/utils/setupTests.js
---
- Implemented Button unit-test
- Implemented IngredientList unit-test
- Implemented ImageUploader unit-test
---
---
- 
---
=> Frontend Unit tests for Button, ImageUploader, IngredientList 

practice-app/backend/fithub/api/views.py, practice-app/backend/fithub/fithub/settings.py, practice-app/frontend/src/config/constants.js, practice-app/frontend/src/pages/ingredients/IngredientsPage.jsx, practice-app/frontend/src/pages/recipes/UploadRecipePage.jsx, practice-app/frontend/src/services/authService.js, practice-app/frontend/src/services/communityService.js, practice-app/frontend/src/services/forumService.js, practice-app/frontend/src/services/recipeService.js, practice-app/frontend/src/services/userService.js
Latest changes are deployed and tested. Seems fine.
=> Deployment fixes

practice-app/frontend/src/__tests__/RecipeDetailPage.test.jsx
---
- RecipeDetailPage.test.jsx added to test folder
---
---
---
- 
---
=> FRONTEND: added unit test for RecipeDetailPage.jsx

practice-app/docker-compose.yml, practice-app/frontend/src/pages/recipes/RecipeEditPage.jsx, practice-app/frontend/src/services/Auth.js, practice-app/frontend/src/services/recipeService.js
=> some forgotten frontend host addresses

practice-app/frontend/src/components/info/TermsContent.jsx, practice-app/frontend/src/components/recipe/RecipeCard.jsx, practice-app/frontend/src/components/ui/Modal.jsx, practice-app/frontend/src/pages/auth/RegisterPage.jsx, practice-app/frontend/src/pages/community/PostDetailPage.jsx, practice-app/frontend/src/pages/info/TermsPage.jsx, practice-app/frontend/src/pages/recipes/RecipeDetailPage.jsx, practice-app/frontend/src/routes/index.jsx, practice-app/frontend/src/services/userService.js, practice-app/frontend/src/styles/AuthPages.css, practice-app/frontend/src/styles/Modal.css, practice-app/frontend/src/styles/RecipeCard.css, practice-app/frontend/src/styles/TermsContent.css, practice-app/frontend/src/styles/TermsPage.css
---
- Author's names are shown on the recipes
- Community page username bug is fixed
- Terms and Conditions are added
---
- GET /api/user{id}
---
---
- 
---
=> Last General fixations
